Enhance CI workflow by adding server start failure handling and reordering curl installation in Dockerfile

diff --git a/.github/workflows/build-and-deploy-ci.yaml b/.github/workflows/build-and-deploy-ci.yaml
--- a/.github/workflows/build-and-deploy-ci.yaml
+++ b/.github/workflows/build-and-deploy-ci.yaml
@@ -30,7 +30,13 @@ jobs:
       - name: Run tests
         run: |
           docker-compose -f server/docker-compose.ci.yaml up -d
+          count=0
           until docker exec server curl -f http://localhost:3000; do
+            if [ $count -gt 5 ]; then
+              echo "Server failed to start"
+              exit 1
+            fi
+            count=$((count+1))
             echo "Waiting for server to start..."
             sleep 5s
           done
