Update CI workflow to use Docker Compose for server setup and improve test execution with enhanced server start checks

diff --git a/.github/workflows/build-and-deploy-ci.yaml b/.github/workflows/build-and-deploy-ci.yaml
--- a/.github/workflows/build-and-deploy-ci.yaml
+++ b/.github/workflows/build-and-deploy-ci.yaml
@@ -9,7 +9,7 @@ jobs:
   test-server:
     env:
       DATABASE_NAME: mocafi-db
-      DB_CONNECTION_STRING: mongodb://root:example@localhost:27017/mocafi-db?authSource=admin
+      DB_CONNECTION_STRING: mongodb://root:example@db:27017/mocafi-db?authSource=admin
       PORT: 3000
       APP_URL: http://localhost:3000
       APP_SECRET: 45ddbeb7ce0b195d592c9e37f46854498f637e7b8747540f192893fd9230d905
@@ -22,19 +22,25 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: setup node
-        uses: actions/setup-node@v4
+      - name: Setup docker compose
+        uses: KengoTODA/actions-setup-docker-compose@v1
         with:
-          node-version: 20
-
-      - name: Install dependencies
-        run: |
-          docker-compose -f server/docker-compose.ci.yaml up -d db migrate
-          npm install
+          version: '2.14.2'
 
       - name: Run tests
         run: |
-          npm run test
+          docker-compose -f server/docker-compose.ci.yaml up -d
+          count=0
+          until docker exec server curl -f http://localhost:3000; do
+            if [ $count -gt 15 ]; then
+              echo "Server failed to start"
+              exit 1
+            fi
+            count=$((count+1))
+            echo "Waiting for server to start..."
+            sleep 5s
+          done
+          docker exec server npm run test
 
   test-client:
     runs-on: ubuntu-latest
